In [ ]:
import numpy as np
print(np.zeros((2,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(np.ones((5,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [ ]:
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [ ]:
print(np.logspace(1,10,4))

[1.e+01 1.e+04 1.e+07 1.e+10]


In [ ]:
print(np.random.rand(4,2))

[[0.98748404 0.5179752 ]
 [0.38643471 0.54912781]
 [0.02510341 0.46110715]
 [0.47711014 0.0585892 ]]
